name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git tag ${{ github.event.inputs.version }} 
          git push origin ${{ github.event.inputs.version }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          draft: true

  macos-aarch64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          zig build -Doptimize=ReleaseSmall -Dtarget=aarch64-macos
          tar -czf zup-macos-aarch64.tar.gz zig-out/bin/zup
          shasum -a 256 zup-macos-aarch64.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          draft: true
          allowUpdates: true
          artifacts: "zup-macos-aarch64.tar.gz"

  macos-x86_64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-macos
          tar -czf zup-macos-x86_64.tar.gz zig-out/bin/zup
          shasum -a 256 zup-macos-x86_64.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          draft: true
          allowUpdates: true
          artifacts: "zup-macos-x86_64.tar.gz"

  linux-aarch64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          zig build -Doptimize=ReleaseSmall -Dtarget=aarch64-linux
          tar -czf zup-linux-aarch64.tar.gz zig-out/bin/zup
          shasum -a 256 zup-linux-aarch64.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          draft: true
          allowUpdates: true
          artifacts: "zup-linux-aarch64.tar.gz"

  linux-x86_64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-linux
          tar -czf zup-linux-x86_64.tar.gz zig-out/bin/zup
          shasum -a 256 zup-linux-x86_64.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          draft: true
          allowUpdates: true
          artifacts: "zup-linux-x86_64.tar.gz"
