name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: git tag ${{ github.event.inputs.version }} 
      - run: git push origin ${{ github.event.inputs.version }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          draft: true

  macos-aarch64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Doptimize=ReleaseSmall -Dtarget=aarch64-macos -Dname=zup-macos-aarch64
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          allowUpdates: true
          artifacts: "zig-out/bin/zup-macos-aarch64"

  macos-x86_64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-macos -Dname=zup-macos-x86_64
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          allowUpdates: true
          artifacts: "zig-out/bin/zup-macos-x86_64"

  linux-aarch64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Doptimize=ReleaseSmall -Dtarget=aarch64-linux -Dname=zup-linux-aarch64
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          allowUpdates: true
          artifacts: "zig-out/bin/zup-linux-aarch64"

  linux-x86_64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-linux -Dname=zup-linux-x86_64
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          allowUpdates: true
          artifacts: "zig-out/bin/zup-linux-x86_64"
