name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: git tag ${{ github.event.inputs.version }} 
      - run: git push origin ${{ github.event.inputs.version }}


  macos-aarch64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Doptimize=ReleaseSmall -Dtarget=aarch64-macos
      - uses: actions/upload-artifact@v4
        with:
          name: zup-macos-aarch64
          path: ./zig-out/bin/zup

  macos-x86_64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-macos
      - uses: actions/upload-artifact@v4
        with:
          name: zup-macos-x86_64
          path: ./zig-out/bin/zup

  linux-aarch64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Doptimize=ReleaseSmall -Dtarget=aarch64-linux
      - uses: actions/upload-artifact@v4
        with:
          name: zup-linux-aarch64
          path: ./zig-out/bin/zup

  linux-x86_64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-linux
      - uses: actions/upload-artifact@v4
        with:
          name: zup-linux-x86_64
          path: ./zig-out/bin/zup
